### ISSUE TITLE
Encounter an error message while loading the functions

### ISSUE THREAD

**Issue by AustinApple** [casperg92/MaSIF_colab#2]
Hello,
I could implement the notebook perfectly on colab last week, but this week I start to encounter the following error message while loading the functions. I guess it is the problem of the version of PyTorch, which has been discussed in the [thread.](https://github.com/rusty1s/pytorch_sparse/issues/207)

```RuntimeError: 
Tried to access nonexistent attribute or method 'crow_indices' of type 'Tensor'.:
  File "/usr/local/lib/python3.7/dist-packages/torch_sparse/tensor.py", line 109
    def from_torch_sparse_csr_tensor(self, mat: torch.Tensor,
                                     has_value: bool = True):
        rowptr = mat.crow_indices()
                 ~~~~~~~~~~~~~~~~ <--- HERE
        col = mat.col_indices()
```

**Comment by casperg92** [comment]
Hi,

Yes unfortunately there has been an upgrade for pytorch geometric which completely broke the colab.
I'm working on a fix, I'll keep you posted!

Best,

Casper

**Comment by casperg92** [comment]
I just pushed a fix for the pytorch geometric versions and it's running again!
Let me know if you run into any other issues.

Cheers,

Casper
